spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/ordertracker?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
